### ISSUE TITLE
RecyclerView's scroll position reset on config change

### ISSUE THREAD

**Issue by oldergod** [JakeWharton/SdkSearch#39] opened 2018-01-17 07:06 UTC
![sdksearch_config_change](https://user-images.githubusercontent.com/1767669/35029909-67a3e0de-fba0-11e7-8b21-53996ed88e91.gif)

**Comment by JakeWharton** [comment] 2018-01-17 18:21
Far too much happens in `onCreate`, but I'll get it refactored eventually. I need to get a layer teased out between something pushing view models and the rendering so that rotation doesn't even trigger a new query.

**Comment by selmanon** [comment] 2018-01-17 21:36
@JakeWharton what do you think about this solution .. if it's fine for you I can work on it

**Comment by oldergod** [comment] 2018-01-18 04:33
> I need to get a layer teased out between something pushing view models and the rendering so that rotation doesn't even trigger a new query.

FWIW, I believe the recyclerview scroll position resets because of the thread switch; after rotation, the layout adapter applies the saved scroll position to a new, _not yet defined_, list of items.

**Comment by JakeWharton** [comment] 2018-01-18 04:40
Right. So a view model available synchronously after rotation will solve
that.

**Comment by amanjeetsingh150** [comment] 2018-01-27 00:19
Hi @JakeWharton ,
First of all thank you for this amazing project. Can we use onSavedInstanceState() method of the layout manager to save state of recycler view when activity is rotated in onSavedInstanceState method of activity and then restoring it appropriately. It will be less tedious I think.
Like mentioned in this link: https://stackoverflow.com/questions/28236390/recyclerview-store-restore-state-between-activities/28262885
Do tell me if I am wrong somewhere.
If this approach seems OK to you I will send a quick PR?

**Comment by JakeWharton** [comment] 2018-01-27 00:30
That should be the default behavior. The problem is that we set an empty
adapter before the actual data shows up on the next frame. A view model
decoupled from the activity lifecycle will make the problem magically go
away.

**Comment by amanjeetsingh150** [comment] 2018-01-27 00:37
Agreed, with this case I'll definitely try the solution with ViewModel.
Thanks :)

**Comment by JakeWharton** [comment] 2018-01-27 00:41
That's lowercase "view model" not the architecture component ViewModel. I
don't understand the purpose of the architecture component existing...

**Comment by michaldrabik** [comment] 2018-02-08 12:23
> That's lowercase "view model" not the architecture component ViewModel. I don't understand the purpose of the architecture component existing...

Do you advise against AAC ViewModel solution here? It could emit view's states here and survive config changes here? Why is that?

**Comment by JakeWharton** [comment] 2018-02-22 04:29
This is almost fixed. The presenter is now retained across rotation and the old results are populated back into the UI. There's just a timing problem now of getting the first model after rotation.

**Comment by JakeWharton** [comment] 2018-03-03 06:51
This is fixed by f9fc452, but the keyboard still pops up on rotation. It'd be nice to retain it's state by having something other than the query edit text hold focus when you interact with the list.

**Comment by JakeWharton** [comment] 2018-03-03 07:56
This doesn't happen on my phone, only emulators. Closing as resolved.

**Closed by JakeWharton** 2018-03-03 07:56 UTC
Labels: bug, platform/android

**Comment by Apsaliya** [comment] 2018-03-11 09:34
Keyboard pops up on rotation thingy happens on current play store version. (on real device)

**Comment by JakeWharton** [comment] 2018-03-30 04:04
What device?

**Comment by Apsaliya** [comment] 2018-03-30 04:20
Xioami MI A1. It has stock 8.0.0 running on it.
